package com.agroservices.model;
// Generated 28-sep-2015 20:46:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="Ventas")
public class Venta  implements java.io.Serializable {


     private Integer idVentas;
     private Campesino campesinos;
     private ProductoEnVenta productosEnVenta;
     private Date fechaVenta;

    public Venta() {
    }

    public Venta(Campesino campesinos, ProductoEnVenta productosEnVenta, Date fechaVenta) {
       this.campesinos = campesinos;
       this.productosEnVenta = productosEnVenta;
       this.fechaVenta = fechaVenta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVentas", unique=true, nullable=false)
    public Integer getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(Integer idVentas) {
        this.idVentas = idVentas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Campesinos_idCampesinos", nullable=false)
    public Campesino getCampesinos() {
        return this.campesinos;
    }
    
    public void setCampesinos(Campesino campesinos) {
        this.campesinos = campesinos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductosEnVenta_idProductosEnVenta", nullable=false)
    public ProductoEnVenta getProductosEnVenta() {
        return this.productosEnVenta;
    }
    
    public void setProductosEnVenta(ProductoEnVenta productosEnVenta) {
        this.productosEnVenta = productosEnVenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaVenta", nullable=false, length=10)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }




}


